### ISSUE TITLE
bash native Error: spawn /usr/local/bin/bash ENOENT

### ISSUE THREAD

**Issue by Akkuma** [mrmlnc/fast-glob#14]
Glob works fine when I force it to not use bashNative via `{ bashNative: [] }`, but fails otherwise
```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn /usr/local/bin/bash ENOENT
    at exports._errnoException (util.js:1018:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

This is on OSX

**Comment by jeremychone** [comment]
Yes, same here. I wish optimization would be opt-in.

**Comment by mrmlnc** [comment]
Hello, @jeremychone and @Akkuma,

You can disable `bash-glob` for `fast-glob` by `{ bashNative: [] }` option. We can wait a https://github.com/micromatch/bash-glob/pull/3 or https://github.com/mrmlnc/fast-glob/issues/15.

**Comment by mrmlnc** [comment]
The `bashNative` mode will be removed from `fast-glob@2`, because has a lot of questions.
