### ISSUE TITLE
2.2.5: UnhandledPromiseRejectionWarning: TypeError: entry.isFile is not a function

### ISSUE THREAD

**Issue by iameli** [mrmlnc/fast-glob#145]
### Environment

  * OS Version: macOS 10.14
  * Node.js Version: v10.13.0

### Actual behavior
I found it when using Parcel on an empty file.

```
▶︎ npx parcel build asdf.js
(node:57579) UnhandledPromiseRejectionWarning: TypeError: entry.isFile is not a function
    at EntryFilter.onlyFileFilter (/Users/iameli/code/floating-hangout/node_modules/fast-glob/out/providers/filters/entry.js:56:49)
    at EntryFilter.filter (/Users/iameli/code/floating-hangout/node_modules/fast-glob/out/providers/filters/entry.js:32:18)
    at /Users/iameli/code/floating-hangout/node_modules/fast-glob/out/providers/filters/entry.js:18:48
    at /Users/iameli/code/floating-hangout/node_modules/fast-glob/out/adapters/fs-sync.js:32:36
    at Array.forEach (<anonymous>)
    at FileSystemSync.read (/Users/iameli/code/floating-hangout/node_modules/fast-glob/out/adapters/fs-sync.js:29:18)
    at ReaderSync.staticApi (/Users/iameli/code/floating-hangout/node_modules/fast-glob/out/providers/reader-sync.js:70:31)
    at ReaderSync.api (/Users/iameli/code/floating-hangout/node_modules/fast-glob/out/providers/reader-sync.js:58:21)
    at ReaderSync.read (/Users/iameli/code/floating-hangout/node_modules/fast-glob/out/providers/reader-sync.js:41:32)
    at Array.map (<anonymous>)
(node:57579) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:57579) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

### Expected behavior
Not crashing

### Steps to reproduce
```
touch empty-file.js
npx parcel empty-file.js
```

**Comment by iameli** [comment]
Oop, got beat by two minutes, closing as dupe of #144
