### ISSUE TITLE
fast-glob@3.2.0 Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by FabienDehopre** [mrmlnc/fast-glob#254]
### Environment

  * OS Version: Windows 10 (17134)
  * Node.js Version: 12.13.1

### Actual behavior
When called by stylelint, immediately crashes with the following message and stack trace:
```
TypeError: Cannot read property 'length' of undefined
    at Object.getPatternParts (c:\Projects\***\node_modules\fast-glob\out\utils\pattern.js:94:20)
    at PartialMatcher._getPatternSegments (c:\Projects\***\node_modules\fast-glob\out\providers\matchers\matcher.js:30:37)
    at PartialMatcher._fillStorage (c:\Projects\***\node_modules\fast-glob\out\providers\matchers\matcher.js:19:35)
    at new Matcher (c:\Projects\***\node_modules\fast-glob\out\providers\matchers\matcher.js:10:14)
    at new PartialMatcher (c:\Projects\***\node_modules\fast-glob\out\providers\matchers\partial.js:4:1)
    at DeepFilter._getMatcher (c:\Projects\***\node_modules\fast-glob\out\providers\filters\deep.js:16:16)
    at DeepFilter.getFilter (c:\Projects\***\node_modules\fast-glob\out\providers\filters\deep.js:11:30)
    at ProviderAsync._getReaderOptions (c:\Projects\***\node_modules\fast-glob\out\providers\provider.js:25:41)
    at ProviderAsync.read (c:\Projects\***\node_modules\fast-glob\out\providers\async.js:12:30)
    at Array.map (<anonymous>)
```

### Expected behavior
Should work as previous version (3.1.1)

### Steps to reproduce

  1. install latest stylelint version
  1. launch stylelint with a command similar to `stylelint **/*.scss --fix --color`

**Comment by xfoxfu** [comment]
In fact just a simple glob breaks:

```
$ node
Welcome to Node.js v13.7.0.
Type ".help" for more information.
> const glob = require("fast-glob")
undefined
> glob.sync("./**/*.ts")
Uncaught TypeError: Cannot read property 'length' of undefined
    at Object.getPatternParts (/Users/coderfox/Dev/Projects/matrix/course-se/node_modules/fast-glob/out/utils/pattern.js:94:20)
    at PartialMatcher._getPatternSegments (/Users/coderfox/Dev/Projects/matrix/course-se/node_modules/fast-glob/out/providers/matchers/matcher.js:30:37)
    at PartialMatcher._fillStorage (/Users/coderfox/Dev/Projects/matrix/course-se/node_modules/fast-glob/out/providers/matchers/matcher.js:19:35)
    at new Matcher (/Users/coderfox/Dev/Projects/matrix/course-se/node_modules/fast-glob/out/providers/matchers/matcher.js:10:14)
    at new PartialMatcher (/Users/coderfox/Dev/Projects/matrix/course-se/node_modules/fast-glob/out/providers/matchers/partial.js:4:1)
    at DeepFilter._getMatcher (/Users/coderfox/Dev/Projects/matrix/course-se/node_modules/fast-glob/out/providers/filters/deep.js:16:16)
    at DeepFilter.getFilter (/Users/coderfox/Dev/Projects/matrix/course-se/node_modules/fast-glob/out/providers/filters/deep.js:11:30)
    at ProviderSync._getReaderOptions (/Users/coderfox/Dev/Projects/matrix/course-se/node_modules/fast-glob/out/providers/provider.js:25:41)
    at ProviderSync.read (/Users/coderfox/Dev/Projects/matrix/course-se/node_modules/fast-glob/out/providers/sync.js:12:30)
    at Array.map (<anonymous>)
```

**Comment by mrmlnc** [comment]
Do you use yarn?

**Comment by xfoxfu** [comment]
@mrmlnc Yes, I use yarn.

```
fast-glob@^3.2.0:
  version "3.2.0"
  resolved "https://registry.yarnpkg.com/fast-glob/-/fast-glob-3.2.0.tgz#8555aac93c882e711ce40f7c24435a2e44c9e56d"
  integrity sha512-x0gdwWaaubNqJ2nQV8YDALCZRiCy9zOEHlF7ScpzalxdxMKh78Qc0lcpZ4w2I0LZUfklA/IQPLlPU36YTgUozA==
  dependencies:
    "@nodelib/fs.stat" "^2.0.2"
    "@nodelib/fs.walk" "^1.2.3"
    glob-parent "^5.1.0"
    merge2 "^1.3.0"
    micromatch "^4.0.2"

```

**Comment by mrmlnc** [comment]
Looks like duplicate for #253.

**Comment by mrmlnc** [comment]
https://github.com/mrmlnc/fast-glob/issues/253#issuecomment-586914257
