### ISSUE TITLE
Fails on Windows

### ISSUE THREAD

**Issue by jdalton** [mrmlnc/fast-glob#63]
Hi! I'm seeing a fail on Windows related to https://github.com/micromatch/micromatch/issues/95#issuecomment-311135073 and `path.sep`. Does this sound like something fast-glob is doing?

The error stack is:
```
C:\projects\esm\node_modules\snapdragon\lib\parser.js:473
        throw new Error('no parsers registered for: "' + self.input.slice(0, 5) + '"');
        ^

.cac": no parsers registered for: "
    at parse (C:\projects\esm\node_modules\snapdragon\lib\parser.js:473:15)
    at Parser.parse (C:\projects\esm\node_modules\snapdragon\lib\parser.js:477:24)
    at Snapdragon.parse (C:\projects\esm\node_modules\snapdragon\index.js:122:28)
    at Snapdragon.<anonymous> (C:\projects\esm\node_modules\fast-glob\node_modules\micromatch\lib\utils.js:47:45)
    at parse (C:\projects\esm\node_modules\fast-glob\node_modules\micromatch\index.js:741:26)
    at memoize (C:\projects\esm\node_modules\fast-glob\node_modules\micromatch\index.js:861:13)
    at Function.micromatch.parse (C:\projects\esm\node_modules\fast-glob\node_modules\micromatch\index.js:747:10)
    at create (C:\projects\esm\node_modules\fast-glob\node_modules\micromatch\index.js:688:44)
    at C:\projects\esm\node_modules\fast-glob\node_modules\micromatch\index.js:697:16
    at memoize (C:\projects\esm\node_modules\fast-glob\node_modules\micromatch\index.js:861:13)
npm ERR! Test failed.  See above for more details.
```

**Comment by jdalton** [comment]
I have a folder named `.cache` that I think it's tripping up on. It's seeing it as an extension. I don't get the error on Mac/Linux though.

**Comment by jdalton** [comment]
Turned out to be an odd regexp parsing bug in Nodechakra.

**Comment by mrmlnc** [comment]
Hello, @jdalton,

In the `fast-glob` package we transform all paths to Unix-way view (`/`) before we start working with them. The `micromatch` package also apply `unixify` function for all paths.

You can provide more information for your case (how to I can reproduce your problem, actual and expected behaviour), for example, use Issue template in this repository.
